# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20170727_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='size',
            field=models.IntegerField(verbose_name='Человек в бригаде'),
        ),
    ]
