# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20170810_1905'),
        ('masters', '0003_auto_20170727_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='profession',
        ),
        migrations.AddField(
            model_name='master',
            name='profession',
            field=models.ManyToManyField(to='orders.Profession', verbose_name='Профессия'),
        ),
    ]
