# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_master_zamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон'),
        ),
    ]
