# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_auto_20170812_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
