# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20170922_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
