# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='proffesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Profession', verbose_name='Профессия'),
        ),
    ]
