# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20170727_1403'),
        ('orders', '0006_order_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master',
        ),
        migrations.AddField(
            model_name='order',
            name='master_changed',
            field=models.ManyToManyField(related_name='master_changed', to='masters.Master', verbose_name='Мастер исполнитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='master_send_sms',
            field=models.ManyToManyField(to='masters.Master', verbose_name='Кому отправить СМС'),
        ),
    ]
