# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170727_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': ' Города'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': '    Заказы'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': '   Профессии'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работу', 'verbose_name_plural': '  Виды работ'},
        ),
        migrations.AlterField(
            model_name='order',
            name='master_changed',
            field=models.ManyToManyField(blank=True, related_name='master_changed', to='masters.Master', verbose_name='Мастер исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_send_sms',
            field=models.ManyToManyField(blank=True, to='masters.Master', verbose_name='Кому отправить СМС'),
        ),
    ]
