# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170803_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proffesion',
        ),
    ]
