# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_proffesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master_send_sms',
        ),
        migrations.AddField(
            model_name='order',
            name='master_send_sms',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кому отправить СМС'),
        ),
    ]
