# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20170805_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_send_sms',
            field=jsonfield.fields.JSONField(blank=True, verbose_name='Кому отправить СМС'),
        ),
    ]
