# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20170805_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_send_sms',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кому отправить СМС'),
        ),
    ]
