# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20170805_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_changed',
            field=models.IntegerField(blank=True, max_length=100, verbose_name='Мастер исполнитель'),
        ),
    ]
