# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20170727_1539'),
        ('orders', '0019_auto_20170805_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master_send_sms',
        ),
        migrations.AddField(
            model_name='order',
            name='master_send_sms',
            field=models.ManyToManyField(blank=True, to='masters.Master', verbose_name='Кому отправить СМС'),
        ),
    ]
