# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20170810_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='enter',
            field=models.CharField(default='Телефон', max_length=300, verbose_name='Вход'),
        ),
    ]
