# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='enter',
            field=models.CharField(max_length=300, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start',
            field=models.DateTimeField(blank=True, verbose_name='Начало работ'),
        ),
    ]
