# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20170812_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнен'), ('2', 'В работе'), ('3', 'Невыполнен'), ('4', 'Отказ')], default='3', max_length=10, verbose_name='Статус'),
        ),
    ]
